document.getElementById("year").textContent=new Date().getFullYear();
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener("click",e=>{const t=document.querySelector(link.getAttribute("href"));if(!t)return;e.preventDefault();t.scrollIntoView({behavior:"smooth",block:"start"})}));
const lb=document.getElementById("lightbox"),lbImg=document.getElementById("lightbox-image"),lbCap=document.getElementById("lightbox-caption");
document.querySelectorAll(".lightbox-trigger").forEach(b=>b.addEventListener("click",()=>{const i=b.querySelector("img");lbImg.src=b.dataset.full||i.src;lbImg.alt=i.alt;lbCap.textContent=i.alt;lb.classList.add("open");lb.setAttribute("aria-hidden","false");document.body.classList.add("no-scroll")}));
function closeLb(){if(!lb)return;lb.classList.remove("open");lb.setAttribute("aria-hidden","true");document.body.classList.remove("no-scroll");lbImg.src=""}
document.querySelector(".lightbox-close")?.addEventListener("click",closeLb);lb?.addEventListener("click",e=>{if(e.target===lb)closeLb()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeLb()});

// Local gallery image adders (preview only; upload to assets/GitHub for permanent storage)
document.querySelectorAll(".image-upload-input").forEach(input=>{input.addEventListener("change",()=>{const gallery=document.querySelector(input.dataset.gallery);if(!gallery)return;[...input.files].forEach(file=>{if(!file.type.startsWith("image/"))return;const url=URL.createObjectURL(file);const card=document.createElement("article");card.className="gallery-card";card.innerHTML='<button class="gallery-image image-button lightbox-trigger" data-full="'+url+'"><img src="'+url+'" alt="'+file.name.replace(/"/g,"&quot;")+'"></button><div class="gallery-info"><div><p class="work-type">New '+(input.dataset.gallery.includes("sculpture")?"Sculpture":"Artwork")+'</p><h3>'+file.name.replace(/</g,"&lt;")+'</h3></div><strong>Custom quotation</strong></div><a class="card-enquire" href="contact.html#enquiry">Enquire ↗</a></article>';gallery.appendChild(card);const btn=card.querySelector(".lightbox-trigger");btn.addEventListener("click",()=>{const i=btn.querySelector("img");if(!lb)return;lbImg.src=url;lbImg.alt=i.alt;lbCap.textContent=i.alt;lb.classList.add("open");lb.setAttribute("aria-hidden","false");document.body.classList.add("no-scroll")});});input.value=""})});

const menuToggle=document.querySelector(".menu-toggle"),siteHeader=document.querySelector(".site-header");
menuToggle?.addEventListener("click",()=>{const open=siteHeader.classList.toggle("nav-open");menuToggle.setAttribute("aria-expanded",String(open));menuToggle.setAttribute("aria-label",open?"Close menu":"Open menu")});
document.querySelectorAll(".nav a").forEach(link=>link.addEventListener("click",()=>{siteHeader?.classList.remove("nav-open");menuToggle?.setAttribute("aria-expanded","false");menuToggle?.setAttribute("aria-label","Open menu")}));
